server:
  port: 8081
spring:
  datasource:
    name: ds1
    url: jdbc:mysql://localhost:3306/amlbst_fat?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mybatis:
    mapperLocations: classpath:mapper/ds1/*Mapper.xml
    configLocation: classpath:mapper/mybatis-config.xml

    name: ds2
        url: jdbc:mysql://localhost:3306/amlbt_fat?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  mybatis:
    mapperLocations: classpath:mapper/ds2/*Mapper.xml
    configLocation: classpath:mapper/mybatis-config.xml

#  ds2:
#    datasource:
#      url: jdbc:mysql://localhost:3306/amlbht_fat?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: classpath:mapper/ds2/*Mapper.xml